apiVersion: v1
kind: ConfigMap
metadata:
  name: snmp-data
  namespace: zabbix-deployment 
data:
  device1.snmprec: |
    1.3.6.1.2.1.1.1.0|4|Simulated Router #1
    1.3.6.1.2.1.1.3.0|67|123456
    1.3.6.1.2.1.1.5.0|4|Router-One
    1.3.6.1.2.1.2.1.0|2|4
  device2.snmprec: |
    1.3.6.1.2.1.1.1.0|4|Simulated Switch #2
    1.3.6.1.2.1.1.3.0|67|234567
    1.3.6.1.2.1.1.5.0|4|Switch-Two
    1.3.6.1.2.1.2.1.0|2|8
  device3.snmprec: |
    1.3.6.1.2.1.1.1.0|4|Simulated Firewall #3
    1.3.6.1.2.1.1.3.0|67|345678
    1.3.6.1.2.1.1.5.0|4|Firewall-Three
    1.3.6.1.2.1.2.1.0|2|2
