#SPDX-License-Identifier: MIT-0
---
# defaults file for zabbix-automation

# Zabbix API credentials
zabbix_api_user: Admin
zabbix_api_password: zabbix

# Zabbix API connection details
zabbix_api_host: localhost
zabbix_api_port: 80
zabbix_api_use_ssl: false
zabbix_api_validate_certs: false
zabbix_api_url_path: ""

# Zabbix server configuration
zabbix_server_agent_ip: 172.168.1.51
zabbix_server_agent_port: "10050"

# Zabbix proxy configuration
zabbix_proxy_agent_ip: 172.168.1.52
zabbix_proxy_agent_port: "10050"
zabbix_proxy_address: 172.168.1.40

# SNMP devices configuration
snmp_device_ips:
  - ip: 172.168.2.21
    name: snmp-sim1
    visible_name: "SNMP Device One"
    port: "161"
    community: "public"
