apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-config
  namespace: zabbix-deployment
data:
  ZBX_SERVER_NAME: "zabbix-server"
  ZBX_SERVER_HOST: "zabbix-server"
  ZBX_HOSTNAME: "Zabbix server"
  ZBX_PROXY_HOSTNAME: "zabbix-snmp-proxy"
  ZBX_AGENT_SERVER_HOST: "127.0.0.1"
  ZBX_SERVER_PORT: "10051"
  PHP_TZ: "Europe/Riga"
  ZBX_DEBUGLEVEL: "4"
  ZBX_ENABLE_SNMP_TRAPS: "true"
  DB_SERVER_HOST: "zabbix"
  MYSQL_DATABASE: "zabbix"
  MYSQL_USER: "zabbix"
  MYSQL_PASSWORD: "zabbix_password"
  MYSQL_ROOT_PASSWORD: "root_password"