---
galaxy_info:
  author: Artis Cevers
  description: Ansible Role to automate Zabbix server and proxy configuration via Zabbix API
  company: Swisscom SDC

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: "2.9"

  galaxy_tags: []

dependencies: []
